import { AppLayout } from '../components/layouts/AppLayout';
import ThemeRegistry from '../components/theme/ThemeRegistry';
import './global.css';

export const metadata = {
  title: 'Football News',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <AppLayout>{children}</AppLayout>
        </ThemeRegistry>
      </body>
    </html>
  );
}
